### ISSUE TITLE
Syntax Highlighting: Issue with operntsdb query filter plugins

### ISSUE THREAD

**Issue by samstradling** [tbutterwith/bosun-vscode#6]
If a filter plugin is used, e.g. `wildcard()`, `literal_or()` etc., this causes the syntax to be highlighted as if the query until that point is a method name:

```bosun
$anotherQuery = sum:a.b.c.d{}{foo=wildcard(b*)}
```

<img width="421" alt="Screenshot 2019-05-21 at 15 40 19" src="https://user-images.githubusercontent.com/9036408/58106073-6a214700-7bdf-11e9-88bb-c81c27f44f2e.png">

This is using `Dark+ (default dark)` theme.

**Comment by tbutterwith** [comment]
It's now highlighting the function within the query. Not sure if that's the right thing to do but I'm going with it for now.

![image](https://user-images.githubusercontent.com/6391616/58940840-79bd9580-8772-11e9-97b2-0c62a22a7e16.png)
